#!/bin/python3

import sys


t = int(input().strip())
for a0 in range(t):
    n = int(input().strip())
    n3=int((n-1)/3)
    n5=int((n-1)/5)
    n15=int((n-1)/15)
    sum3=3*(n3*(n3+1))
    sum5=5*(n5*(n5+1))
    sum15=15*(n15*(n15+1))
    ans=(sum3+sum5-sum15)//2
    print(int(ans))
