#!/bin/python3

import sys


t = int(input().strip())

def checkprime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True
for a0 in range(t):
    n = int(input().strip())
    max=0
    flag=0
    for i in range(1,(n+1)):
        if(n%i==0):
            div=n//i;
            if (checkprime(div)):
                print(div)
                flag=1
        if(flag==1):
            break
