#!/bin/python3

import sys


t = int(input().strip())
for a0 in range(t):
    n = int(input().strip())
    sum=(n*(n+1))/2
    ans=0
    for i in range(1,n+1):
        ans+=(i)*(sum-i)
    print(int(ans))
            
